# Generated by Django 3.2.7 on 2021-09-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20210925_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(max_length=20)),
                ('lon', models.FloatField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Latitude',
        ),
        migrations.DeleteModel(
            name='LatitudeForm',
        ),
        migrations.DeleteModel(
            name='Longitude',
        ),
        migrations.DeleteModel(
            name='LongitudeForm',
        ),
    ]
